docs/DevelopmentPlan/DevelopmentPlan.tex

Finished part 4 and 5 for the development plan document

[DELIVERABLE 1] Documentation Plan: Add Section 4 and Section 5

---

docs/Common.tex
docs/DevelopmentPlan/DevelopmentPlan.tex

Finished introduction + section 6 in the development plan document.

[DELIVERABLE 1] Development Plan: Add Introduction + Section 6

---

LICENSE

Restricts free access of software

[DELIVERABLE 1] Updated License.txt

---

.github/pull_request_template.md

Adds a default PR template, so they all have a similar layout (like the one used here)
I followed this [link](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository), so it should work for future PRs once this is merged

Create pull_request_template.md to Format PRs

---

docs/ProblemStatementAndGoals/ProblemStatement.tex

Added the challenge level + extra section in the ProblemStatement.tex file

[DELIVERABLE 1] Problem Statement: Added Challenge Level + Extras

---

docs/DevelopmentPlan/DevelopmentPlan.tex

---
name: Default PR
about: Default PR format.
---
Added individual reflection for Tanveer Brar 
File has been compiled locally and there are no issues

[DELIVERABLE 1] Development Plan : Add Tanveer Brar Reflection

---

docs/DevelopmentPlan/DevelopmentPlan.tex

Completed the Accountability and Teamwork section for the Team Charter
Complied on Overleaf

[Deliverable 1] Development Plan : Added Team Charter Bottom Portion

---

docs/DevelopmentPlan/DevelopmentPlan.tex

Answers the first 4 questions in the team charter

[DELIVERABLE 1] Development Plan: Added Team Charter Top Portion

---

docs/ProblemStatementAndGoals/ProblemStatement.tex

Added Goals and Stretch Goals to Problem Statement (Sections 2 and 3) 
Compiled and verified on local

[Deliverable 1] Problem Statement : Add Sections 2 & 3

---

docs/DevelopmentPlan/DevelopmentPlan.tex
docs/ProblemStatementAndGoals/ProblemStatement.tex

Added Nivetha's reflections for both the problem statement and development plan documents

[DELIVERABLE 1] Development Plan + Problem Statement: Added Nivetha's Reflections

---

docs/DevelopmentPlan/DevelopmentPlan.tex

Added expected technologies and coding standard
Tested locally by converting to PDF

[DELIVERABLE 1] Development Plan : Added Sections 10 & 11

---

docs/ProblemStatementAndGoals/ProblemStatement.tex

Goals: changed from PyCharm Plugin to VS Code
Added Individual Reflection
Tested locally

[DELIVERABLE 1]: Problem Statement : Changed Goals, Added Reflection

---

.github/pull_request_template.md

Removed the header since it was appearing in the default template
Should work

Removed the header in pull_request_template.md

---

docs/SRS/SRS.tex

[Deliverable 2] SRS: Tasks Section

---

docs/SRS/SRS.tex

Added the looks and feels requirements. Closes #57.

[DELIVERABLE 2] SRS Document: Looks and Feels Requirements

---

docs/SRS/SRS.tex

Completed sections 3.1, 3.6, 3.7, and 3.8 of Mandated Constraints. Will make a separate PR (?) to finish the rest of the sections. Should partially address #73.

[DELIVERABLE 2] SRS Document: Mandated Constraints 3.1, 3.6, 3.7, 3.8

---

docs/SRS/SRS.tex

Added Security Requirements 
Compiled locally 
Closes #60

[DELIVERABLE 2] SRS Document: Security Requirements 

---

docs/SRS/SRS.tex

Added rational and formatted looks and feels requirements. Related to issue #57 

[DELIVERABLE 2] SRS Document: Formatted Looks and Feels Requirements

---

docs/SRS/SRS.tex

Add priority levels for Looks and Feels Requirements 

[DELIVERABLE 2] SRS Document: Add Priority for Looks and Feels Requirements 

---

docs/SRS/SRS.tex

Added the rationale, and priority levels and also changed the reqs format for Performance Requirements.

[DELIVERABLE 2] SRS Document: Add Rationale + Priority and Changed Formatting for Performance Requirements

---

docs/SRS/SRS.tex

Added the rationale, and priority levels and also changed the reqs format for Usability Requirements.

[DELIVERABLE 2] SRS Document: Add Rationale + Priority and Changed Formatting for Usability Requirements

---

docs/SRS/SRS.tex

Add priority levels for functional requirements. 
TODO: Add citation for one of the requirements

[DELIVERABLE 2] SRS Document: Add Priority for Functional Requirements

---

docs/SRS/SRS.tex

Added Migration to the new Product section. Should close #108.

[DELIVERABLE 2] SRS Document: Migration to the new Product

---

docs/SRS/SRS.tex

[DELIVERABLE 2] SRS: Business Rules

---

docs/HazardAnalysis/HazardAnalysis.tex
refs/References.bib

Added intro and scope and purpose of hazard analysis 
Closes #145 
This is documentation - not applicable

[Deliverable 3] Hazard Analysis: Intro and scope/ purpose 

---

docs/HazardAnalysis/HazardAnalysis.tex

- Added system boundary and components
closes #144

[DELIVERABLE 3] Hazard Analysis: System Boundaries and Components

---

docs/HazardAnalysis/HazardAnalysis.tex

Added safety and security requirements based on FMEA table. Probably would need to update this + add associated hazards once the table is complete.

[DELIVERABLE 3] Hazard Analysis: Safety and Security Requirements (incomplete)

---

docs/HazardAnalysis/HazardAnalysis.tex

Heavily modified the Security Requirements. Added a requirement for all hazards listed in the FMEA table + removed requirements that were already listed in the SRS. Should hopefully close #148. 

[DELIVERABLE 3] Hazard Analysis: Heavily Modified Security Requirements to Match FMEA Table

---

docs/HazardAnalysis/HazardAnalysis.tex

Added roadmap for current and future implementation
Locally compiled

[DELIVERABLE 3] Hazard Analysis: Roadmap

---

docs/HazardAnalysis/HazardAnalysis.tex

Added Critical Assumptions for Hazard Analysis 
Compiled locally 
Closes #159

[DELIVERABLE 3] Hazard Analysis: Critical Assumptions 

---

docs/HazardAnalysis/HazardAnalysis.tex

- Added FMEA Table
- Fixed spelling errors

[DELIVERABLE 3] HA: Final Draft

---

docs/VnVPlan/VnVPlan.tex

Added in SRS verification plan and checklist

[DELIVERABLE 4] VNV Plan: SRS Verification Plan

---

docs/VnVPlan/VnVPlan.tex

Added design verification plan and checklist

[DELIVERABLE 4] VNV Plan: Design Verification Plan

---

docs/VnVPlan/VnVPlan.tex
refs/References.bib

- Added the general information section
closes #182

[DELIVERABLE 4] VnV Plan: General Information

---

docs/VnVPlan/VnVPlan.tex

Functional requirements section 4.1 added 
Traceability between test cases and modules added for Functional Tests 5.4
N/A this is documentation.

[DELIVERABLE 5] VnV Plan: Functional Requirement Tests Section 4.1 + 5.4

---

docs/VnVPlan/VnVPlan.tex
refs/References.bib

Added automated testing and verification tools section
Closes #177

[DELIVERABLE 4] VnV Plan: Automated Testing & Verification Tools

---

docs/VnVPlan/VnVPlan.tex

Added software validation plan 
Closes #181

[DELIVERABLE 4] VnV Plan: Added Software Validation Plan 

---

docs/VnVPlan/VnVPlan.tex
refs/References.bib

- Added System Tests for Non-Functional Requirements
- Added Traceability between NFRs and tests
- Added Survey for tests in Appendix

[DELIVERABLE 4] VnV Plan: System Tests for NFRs + Traceability + Appendix Survey

---

docs/VnVPlan/VnVPlan.tex

Completed sections 3.1, 3.4, and 3.5 in the VnV Plan. Should close #175 #178 #180 

[DELIVERABLE 4] VnV Plan: All Nivetha's Sections

---

docs/VnVPlan/VnVPlan.tex
refs/References.bib

Reflection PR
N/A its documentation

[DELIVERABLE 4] Reflections

---

docs/Comments.tex
docs/VnVPlan/VnVPlan.tex

- Made final formatting and grammar changes

[DELIVERABLE 4] VnV Plan: Final Draft

---

docs/Design/SoftArchitecture/MG.tex
docs/Design/SoftDetailedDes/MIS.tex

Added MIS & MG for User Interfaces Closes

[DESIGN] MIS for User Interfaces Closes #295

---

docs/Design/SoftDetailedDes/MIS.tex

Added fix for LaTeX error which we assumed was a file too long problem
Compiled locally with success

[DESIGN]: Fix for LaTeX error 

---

docs/VnVPlan/VnVPlan.tex

- Added unit test plan for the plugin smell detection command module
- Added unit test plan for the document hashing module
- Added unit test plan for the file highlighting module
- Compiled locally 
closes #380, #382, #414

[VnV Plan] Unit Tests: Smell Detection Command, Hash Documents & File Highlighting

---

docs/VnVPlan/VnVPlan.tex

- Added unit test plan for the smell detection API endpoint
- Added unit test plan for the refactor API endpoint

[VnV Plan] Unit Tests: Detection Endpoint & Refactor Endpoint

---

docs/VnVPlan/VnVPlan.tex

- Added unit test plan for the MIM refactorer

[VnV Plan] Unit Tests: Member Ignoring Method Smell Refactoring

---

docs/VnVPlan/VnVPlan.tex

- Added test description for detection of lec smell module
- Added test description for refactoring of lec smell module
- Added test description for refactoring controller module
- Added test description for hover manager module
- Added test description for line selection manager module

[VnV Plan] Unit Tests: LEC Checker, LEC Refactorer, Refactoring Controller, HoverManager, LineSelectionManager

---

docs/VnVReport/VnVReport.tex

- Added unit tests report for API detection endpoint
- Added unit tests report for API refactoring endpoint
- Added unit tests report for SCL analyzer
- Added unit tests report for SCL refactorer
- Added unit tests report for MIM refactorer
- Added unit tests report for plugin smell detection module
- Added unit tests report for plugin file highlighting module
- Added unit tests report for plugin file hashing module

[VnV Report] Detection + Refactor Route, SCL Refactor + Checker, MIM Refactor, Highlight, Plugin Detect, Hash

---

docs/VnVPlan/VnVPlan.tex

Reformatted and removed duplicate sections. Made unit test consistent format (i.e., goal, bullet point format, etc),

[VNV-PLAN] Reformatted Unit Tests in VnV-Plan

---

docs/VnVPlan/VnVPlan.tex

Unit test documentation for LLE checker & refactorer and LMC checker & refactorer
NA

Unit test documentation for LLE checker & refactorer and LMC checker

---

docs/VnVPlan/VnVPlan.tex

Updated Vnv-plan with above tests
Should close: #400, #404, #407, #415, #411

[VNV-PLAN] Added tests for CRC Analyzer, CRC Refactorer, UGEN Refactorer, Analyzer Controller, and Handle Smells Settings

---

docs/VnVPlan/VnVPlan.tex

Removed unnecessary tests to match vnv-report
Compile locally

[VNV-PLAN] Trimmed out Functional and Non-Functional Requirements Test from VnV Plan

---

docs/VnVReport/VnVReport.tex

Added above tests to report
Issue: https://github.com/ssm-lab/capstone--source-code-optimizer/issues/421

[VNV-REPORT] Added Unit Tests for CRC Refactorer, Detector, UGEN Detector, Analyzer Controller, and Handle Smells Settings

---

docs/VnVReport/VnVReport.tex

- Made small additions and fixes
- Formatting and style tweaks
- Spelling fixes
fixes #375

[VnV Report] Final Draft

---

docs/VnVReport/VnVReport.tex

Added unit test cases for the following:
- LPL Refactorer
- Plugin Wipe Workspace Cache
- Plugin Refactor Smells 
- Plugin Backend
- CodeCarbon Returns Measurement 

[VnV Report] LPL Refactorer + Plugin Wipe Cache + Plugin Refactor Smell + Plugin Backend + Code Carbon Returns 

---

docs/VnVReport/VnVReport.tex

- Added maintainability reqs  tests summary
- Added support reqs tests summary
Compiled Locally

[VnV Report] Maintainability & Support Tests Summary

---

docs/VnVPlan/VnVPlan.tex

Removed cultural reqs from vnv plan
Added reason for removing

[VnV Plan] Removed Cultural Reqs from Plan

---

docs/VnVReport/VnVReport.tex

Added report for Security Requirements

[VnV Report] Added report for Security Requirements

---

docs/VnVPlan/VnVPlan.tex

Updated compliance rq
Compiled locallhy
fixes #466

[VnV Plan] Updated compliance rq

---

docs/VnVReport/VnVReport.tex

Added report for Compliance Requirements

[VnV Report] Added report for Compliance Requirements 

---

docs/VnVPlan/VnVPlan.tex

Fixed no indent

---

docs/Extras/UserManual/README.md
plugin/README.md

Updated README.md in the Extra Usability Folder
N/A

[EXTRA] Added Reference to Wiki for the User Manual
